package customfields;

import com.portal.pcm.StrField;

/**
 * Specific Field subclasses. This subclasses of <code>Field</code>
 * is used with the FList class to specifiy which field is being
 * accessed, and its type.  The type information is used to provide
 * compile time type checking.  These classes are auto generated.
 * @version 1.0 Thu Jun 04 16:10:27 BST 2020
 * @author Autogenerated
 */


public class CFldOlCustomField extends StrField {

	/**
	 * Constructs an instance of <code>CFldOlCustomField</code>
	 */
	public CFldOlCustomField() { super(10000, 5); }

	/**
	 * Returns an instance of <code>CFldOlCustomField</code>
	 * @return An instance of <code>CFldOlCustomField</code>
	 */
	public static synchronized CFldOlCustomField getInst() { 
		if( me == null ) me = new CFldOlCustomField();
		return me;
	}
	private static CFldOlCustomField me;
}
